### ISSUE TITLE
test error when I run Densenet_testway.py

### ISSUE THREAD

**Issue by macqueen09** [whywhs/Pytorch-Handwritten-Mathematical-Expression-Recognition#13]
Firstly , this work is very useful for me. Thanks.

when I run Densenet_testway.py 
I fond there is no `encoder_lr0.00001_BN_te1_d05_SGD_bs8_mask_conv_bn_b.pkl`
and `attn_decoder_lr0.00001_BN_te1_d05_SGD_bs8_mask_conv_bn_b.pkl`
The author delete them  , should I change it in 
`encoder_lr0.00001_GN_te1_d05_SGD_bs6_mask_conv_bn_b_xavier.pkl
attn_decoder_lr0.00001_GN_te1_d05_SGD_bs6_mask_conv_bn_b_xavier.pkl
` which is under `./model` ?

when I load two model under ./model
and then run Densenet_testway.py 
there are error happen. How can I make it work , thanks.

**Comment by macqueen09** [comment]
python Densenet_testway.py 
`
total words/phones 112
total  925 batch data loaded
ignore 61 images
Traceback (most recent call last):
  File "Densenet_testway.py", line 157, in <module>
    attn_decoder1.load_state_dict(torch.load('model/encoder_lr0.00001_GN_te1_d05_SGD_bs6_mask_conv_bn_b_xavier.pkl'))
  File "/home/makaili3/miniconda3/envs/mp6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DataParallel:

	Missing key(s) in state_dict:
"module.embedding.weight", "module.gru.weight_ih", "module.gru.weight_hh", "module.gru.bias_ih", "module.gru.bias_hh", "module.gru1.weight_ih", "module.gru1.weight_hh", "module.gru1.bias_ih", "module.gru1.bias_hh", "module.out.weight", "module.out.bias", "module.hidden.weight", "module.hidden.bias", "module.emb.weight", "module.emb.bias", "module.conv1.weight", "module.conv1.bias", "module.conv_et.weight", "module.conv_et.bias", "module.conv_tan.weight", "module.conv_tan.bias", "module.hidden2.weight", "module.hidden2.bias", "module.emb2.weight", "module.emb2.bias", "module.ua.weight", "module.ua.bias", "module.uf.weight", "module.uf.bias", "module.v.weight", "module.v.bias", "module.wc.weight", "module.wc.bias", "module.bn.weight", "module.bn.bias", "module.bn.running_mean", "module.bn.running_var", "module.bn1.weight", "module.bn1.bias", "module.bn1.running_mean", "module.bn1.running_var". 

	Unexpected key(s) in state_dict:
"module.features.conv0_m.weight", "module.features.norm0.weight", "module.features.norm0.bias", "module.features.norm0.running_mean", "module.features.norm0.running_var", "module.features.norm0.num_batches_tracked", "module.features.denseblock1.denselayer1.norm1.weight", "module.features.denseblock1.denselayer1.norm1.bias", "module.features.denseblock1.denselayer1.norm1.running_mean", "module.features.denseblock1.denselayer1.norm1.running_var", "module.features.denseblock1.denselayer1.norm1.num_batches_tracked", "module.features.denseblock1.denselayer1.conv1.weight", "module.features.denseblock1.denselayer1.norm2.weight", "module.features.denseblock1.denselayer1.norm2.bias", "module.features.denseblock1.denselayer1.norm2.running_mean", "module.features.denseblock1.denselayer1.norm2.running_var", "module.features.denseblock1.denselayer1.norm2.num_batches_tracked", "module.features.denseblock1.denselayer1.conv2.weight", "module.features.denseblock1.denselayer2.norm1.weight", "module.features.denseblock1.denselayer2.norm1.bias", "module.features.denseblock1.denselayer2.norm1.running_mean", "module.features.denseblock1.denselayer2.norm1.running_var", "module.features.denseblock1.denselayer2.norm1.num_batches_tracked", "module.features.denseblock1.denselayer2.conv1.weight", "module.features.denseblock1.denselayer2.norm2.weight", "module.features.denseblock1.denselayer2.norm2.bias", "module.features.denseblock1.denselayer2.norm2.running_mean", "module.features.denseblock1.denselayer2.norm2.running_var", "module.features.denseblock1.denselayer2.norm2.num_batches_tracked", "module.features.denseblock1.denselayer2.conv2.weight", "module.features.denseblock1.denselayer3.norm1.weight", "module.features.denseblock1.denselayer3.norm1.bias", "module.features.denseblock1.denselayer
`
.........
and so on

missing some key in model 
and Unexpected some key(s)

**Comment by macqueen09** [comment]
Python 3.6
pytorch 1.4.0  py3.6_cuda10.1.243_cudnn7.6.3_0
torchvision 0.5.0
GPU: Tesla P100

**Comment by whywhs** [comment]
感谢关注我的工作。
看到你的问题之后，我重新下载了一遍我的代码，重新跑了一下。你把那个模型改了是对的，因为之前那个我删掉之后忘了在Densenet_testway下面改。改了之后，我是可以正常运行的。所以，我觉得有可能是你的pytorch版本太高导致的，建议你使用pytorch 1.1.0.

**Comment by macqueen09** [comment]
哎。。。感谢作者。这个问题最后发现是个人加载模型错误，与代码无关
on `pytorch 1.4.0 py3.6_cuda10.1.243_cudnn7.6.3_0`
it can be used correctly
after run Densenet_testway.py
wer is 0.17188
sacc is 0.38162

**Comment by macqueen09** [comment]
我之后想尝试下在普通RGB 图像上进行特定公式的训练。因为公式类型较少，所以打算自定义少量latex语法，精简符号集，甚至去掉frac这样的语法，用简单的除号代替，满足需求即可。
我打算先写些脚本，把RGB通过二值化变成bmp
以及再试一下改网络输入，微调前面几层维度，使网络输入RGB
这两个尝试点，作者有什么建议嘛

**Comment by whywhs** [comment]
你直接改成三通道的输入就好了，如果你都是RGB图像，没必要专门转成二值图像

**Comment by macqueen09** [comment]
统计了下，改三通道的话，需要在好几个文件里更新超参数
gen_pkl.py
```python
        mat = numpy.zeros([channels, im.shape[0], im.shape[1]], dtype='uint8')
        for channel in range(channels):
            image_file = image_path + key
            im = imread(image_file)
            mat[channel,:,:] = im[:,:,channel]
```
Densenet_torchvision.py
`
 ('conv0_m', nn.Conv2d(channel*2, num_init_features, kernel_size=7, stride=2, padding=3, bias=False)) # channel=3
`
Train.py
```
class custom_dset():
...
train_setting = train_setting.view(size[1],size[2],size[3]) 
```
and
```
def collate_fn():
...
img_mask_sub_s = torch.ones(channel,img_size_h,img_size_w).type(torch.FloatTensor) # change channel
```



模型正在训练ing
非常感谢作者的工作
期待有一个好结果，如果在某处有改进或者效果提升，我也会在发布一个更新在github上的。
